verbose: false
instrumentation:
    root: .
    default-excludes: true
    excludes: ['Gruntfile.js','grunt-comparison.js','task-1.js','task-2.js','task-3.js']
    embed-source: false
    variable: __coverage__
    compact: false
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
    preload-sources: true
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 95]
        lines: [50, 95]
        functions: [50, 95]
        branches: [50, 95]
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false